server:
  port: 8003
  
mybatis:  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.github.springcloud.entities
  mapper-locations:  - classpath:mybatis/mapper/*.xml

spring:  application:    name: microservicecloud-dept
  datasource:    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB3
    username: root
    password: 123
    dbcp2:      min-idle: 5
      initial-size: 5
      max-total: 5

eureka:  client:   #将客户端入驻到eureka中    service-url:      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:    instance-id: microservicecloud-dept8003   #自定义服务器名称
    prefer-ip-address: true   #显示ip地址

info:
  app.name: github-microservicecloud
  company.name: www.github.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$